### ISSUE TITLE
Library not load

### ISSUE THREAD

**Issue by Lineaire** [HallieBot/battibar#1]
Hi ! 

I am learning development and your project seems easy to learn.

I installed your .deb but the libcolorpicker.dylib library and the BattiBarPrefs image not found makes the project untestable

**Comment by ha1lie** [comment]
Hello, and good luck learning tweak development. I'm confused by your comment, as you're stating you installed the deb(eg. the finished executable you need to test it), but you are also claiming that it is untestable? If you installed from a precompiled deb, then you need to make sure you have installed the correct dependencies(found in the `control` file. As far as an image you are claiming is missing, I see all three icon images found in the resources folder of the preferences directory. 


This project was last built when it was stated for release, and I have been out of the tweak development community for some time now. If you'd like to see the finished product, I suggest you install it from the repository(either Packix of Havoc, I haven't kept up to date on the switch) to ensure you have all dependencies. I would suggest reaching out to an active developer for more up to date information. 

Best of luck

Issue closed, as with given information there is not enough to fix a possibly non-issue.
